openapi: 3.0.1
servers:
  - url: https://robokop.renci.org/ranker/api/
components:
  schemas:
    Query:
      x-body-name: request_body
      type: object
      properties:
        message:
          $ref: '#/components/schemas/Message'
      required:
        - message
    Message:
      type: object
      properties:
        results:
          description: List of all returned potential answers for the query posed
          type: array
          items:
            $ref: '#/components/schemas/Result'
        query_graph:
          type: object
          description: >-
            QueryGraph object that contains a serialization of a query in the form
            of a graph
          $ref: '#/components/schemas/QueryGraph'
        knowledge_graph:
          type: object
          description: >-
            KnowledgeGraph object that contains all the nodes and edges referenced
            in any of the possible answers to the query OR connection information
            for a remote knowledge graph
          oneOf:
            - $ref: '#/components/schemas/KnowledgeGraph'
            - $ref: '#/components/schemas/RemoteKnowledgeGraph'
    Result:
      type: object
      description: One of potentially several results or answers for a query
      properties:
        node_bindings:
          type: array
          description: List of QNode-KNode bindings.
          items:
            $ref: '#/components/schemas/NodeBinding'
        edge_bindings:
          type: array
          description: List of QEdge-KEdge bindings.
          items:
            $ref: '#/components/schemas/EdgeBinding'
        score:
          type: number
          format: float
          description: Any type of score associated with this result
          example: 163.233
      required:
        - node_bindings
        - edge_bindings
    NodeBinding:
      type: object
      properties:
        qg_id:
          type: string
        kg_id:
          oneOf:
            - type: string
            - type: array
              items:
                type: string
      required:
        - qg_id
        - kg_id
    EdgeBinding:
      type: object
      properties:
        qg_id:
          type: string
        kg_id:
          oneOf:
            - type: string
            - type: array
              items:
                type: string
      required:
        - qg_id
        - kg_id
    KnowledgeGraph:
      type: object
      description: >-
        A thought graph associated with this result. This will commonly be a
        linear path subgraph from one concept to another, but related items aside
        of the path may be included.
      properties:
        nodes:
          type: array
          description: List of nodes in the KnowledgeGraph
          items:
            $ref: '#/components/schemas/KNode'
        edges:
          type: array
          description: List of edges in the KnowledgeGraph
          items:
            $ref: '#/components/schemas/KEdge'
      required:
        - nodes
        - edges
    RemoteKnowledgeGraph:
      type: object
      description: >-
        A thought graph associated with this result that is not repeated here, but
        stored elsewhere in a way that can be remotely accessed by the reader of
        this Message
      properties:
        url:
          type: string
          example: 'http://robokop.renci.org/api/kg'
          description: URL that provides programmatic access to the remote knowledge graph
        credentials:
          type: object
          description: >-
            Credentials needed for programmatic access to the remote knowledge
            graph
          $ref: '#/components/schemas/Credentials'
      required:
        - url
        - credentials
    Credentials:
      description: Credentials needed for programmatic access to the remote knowledge graph
      type: object
      required:
        - username
        - password
      properties:
        username:
          description: Username needed for programmatic access to the remote knowledge graph
          type: string
        password:
          type: string
          description: Password needed for programmatic access to the remote knowledge graph
    QueryGraph:
      type: object
      description: >-
        A graph intended to be the thought path to be followed by a reasoner to
        answer the question. This graph is a representation of a question.
      properties:
        nodes:
          type: array
          description: List of nodes in the QueryGraph
          items:
            $ref: '#/components/schemas/QNode'
        edges:
          type: array
          description: List of edges in the QueryGraph
          items:
            $ref: '#/components/schemas/QEdge'
      required:
        - nodes
        - edges
    QNode:
      type: object
      description: A node in the QueryGraph
      properties:
        id:
          type: string
          description: >-
            QueryGraph internal identifier for this QNode. Recommended form: n00,
            n01, n02, etc.
          example: n00
        curie:
          oneOf:
            - type: string
            - type: array
              items:
                type: string
          description: CURIE identifier for this node
          example: 'OMIM:603903'
        type:
          oneOf:
            - $ref: '#/components/schemas/BiolinkEntity'
            - type: array
              items:
                $ref: '#/components/schemas/BiolinkEntity'
              description: 'Entity types of this node (e.g., protein, disease, etc.)'
              example:
                - disease
                - genetic_condition
      required:
        - id
    QEdge:
      type: object
      description: An edge in the QueryGraph
      properties:
        id:
          type: string
          description: >-
            QueryGraph internal identifier for this QEdge. Recommended form: e00,
            e01, e02, etc.
          example: e00
        type:
          oneOf:
            - $ref: '#/components/schemas/BiolinkRelation'
            - type: array
              items:
                $ref: '#/components/schemas/BiolinkRelation'
        source_id:
          type: string
          description: Corresponds to the @id of source node of this edge
        target_id:
          type: string
          description: Corresponds to the @id of target node of this edge
      required:
        - id
        - source_id
        - target_id
    KNode:
      type: object
      description: A node in the thought subgraph
      properties:
        id:
          type: string
          description: CURIE identifier for this node
          example: 'OMIM:603903'
        name:
          type: string
          description: Formal name of the entity
          example: Haptoglobin
        type:
          type: array
          description: 'Entity type of this node (e.g., protein, disease, etc.)'
          items:
            type: string
          example:
            - protein
      required:
        - id
    KEdge:
      type: object
      description: An edge in the thought subgraph linking two nodes
      properties:
        id:
          type: string
          description: >-
            Local identifier for this node which is unique within this
            KnowledgeGraph, and perhaps within the source reasoner's knowledge
            graph
          example: '553903'
        type:
          $ref: '#/components/schemas/BiolinkRelation'
        source_id:
          type: string
          description: Corresponds to the @id of source node of this edge
          example: 'https://omim.org/entry/603903'
        target_id:
          type: string
          description: Corresponds to the @id of target node of this edge
          example: 'https://www.uniprot.org/uniprot/P00738'
      required:
        - id
        - source_id
        - target_id
    BiolinkEntity:
      description: A subclass of named_thing (snake_case)
      type: string
      externalDocs:
        description: Biolink model entities
        url: https://biolink.github.io/biolink-model/docs/NamedThing.html
      example: disease
    BiolinkRelation:
      description: A relation, i.e. child of related_to (snake_case)
      type: string
      externalDocs:
        description: Biolink model relations
        url: https://biolink.github.io/biolink-model/docs/related_to.html
      example: affects
info:
  contact:
    email: patrick@covar.com
    name: Patrick Wang
    url: robokop.renci.org
  description: An API for answering biomedical questions
  termsOfService: https://robokop.renci.org/termsofservice/
  title: ROBOKOP Ranker
  version: 0.0.1
  x-reasoner_standard_version: 0.9.1
tags:
  - name: "0.9.2"
  - name: translator
  - name: reasoner
paths:
  /query/:
    post:
      parameters:
        - description: Maximum number of results to return. Provide -1 to indicate no maximum.
          in: query
          name: max_results
          schema:
            type: integer
            default: -1
        - description: 'Requested output format. DENSE, MESSAGE, CSV or ANSWERS'
          in: query
          name: output_format
          schema:
            type: string
            default: MESSAGE
        - description: 'Max connectivity of nodes considered in the answers, Use -1 for no restriction'
          in: query
          name: max_connectivity
          schema:
            type: integer
            default: -1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'
            example:
              message:
                  query_graph:
                      nodes:
                        - id: "n00"
                          type: "disease"
                          curie: "MONDO:0005737"
                        - id: "n01"
                          type: "gene"
                          set: true
                        - id: "n02"
                          type: genetic_condition
                      edges:
                        - id: "e00"
                          source_id: "n00"
                          target_id: "n01"
                        - id: "e01"
                          source_id: "n01"
                          target_id: "n02"
        description: A message with question graph.
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
          description: A message with knowledge graph and answers.
      summary: Get answers to a question
      tags:
        - "0.9.2"
