openapi: '3.0.0'
info:
  version: '0.1.1'
  title: BioLink API
  description: >-
    API integration layer for linked biological objects.
  termsOfService: https://github.com/monarch-initiative/biolink-api/
  contact:
    name: Chris Mungall
    x-role: responsible developer
    email: cjm@berkeleybop.org
    x-id:
      - 'https://orcid.org/0000-0002-6601-2165'
      - 'https://github.com/cmungall'
servers:
  - url: 'https://api.monarchinitiative.org/api'
    description: 'Production server'
tags:
  - name: disease
  - name: gene
  - name: phenotype
  - name: annotation
  - name: query
  - name: translator
paths:
  '/bioentity/disease/{diseaseid}/genes':
    get:
      summary: 'Returns genes associated with a disease'
      parameters:
        - name: diseaseid
          in: path
          description: >-
            CURIE identifier of disease, e.g. OMIM:605543, DOID:678. Equivalent IDs can be used with same results
          required: true
          schema:
            type: string
          x-valueType:
            - 'http://identifiers.org/omim.disease/'
            - 'http://identifiers.org/doid/'
          x-requestTemplate:
            - valueType: 'http://identifiers.org/omim.disease/'
              template: /bioentity/disease/OMIM:{diseaseid}/genes
            - valueType: 'http://identifiers.org/doid/'
              template: /bioentity/disease/{diseaseid}/genes
      responses:
        '200':
          description: 'A distinct set of association.objects (typically ontology terms). This appears at the top level of the results payload'
          x-responseValueType:
            - path: objects
              valueType: 'http://identifiers.org/ncbigene/'
            - path: objects
              valueType: 'http://identifiers.org/hgnc/'
          x-JSONLDContext:
            'biolink/jsonld_context/biolinks_gene_context.json'
  '/bioentity/disease/{diseaseid}/phenotypes':
    get:
      summary: 'Returns phenotypes associated with a disease'
      parameters:
        - name: diseaseid
          in: path
          description: >-
            CURIE identifier of disease, e.g. OMIM:605543, DOID:678. Equivalent IDs can be used with same results
          required: true
          schema:
            type: string
          x-valueType:
            - 'http://identifiers.org/omim.disease/'
            - 'http://identifiers.org/doid/'
            - 'http://identifiers.org/orphanet/'
          x-requestTemplate:
            - valueType: 'http://identifiers.org/omim.disease/'
              template: /bioentity/disease/OMIM:{diseaseid}/phenotypes/
            - valueType: 'http://identifiers.org/orphanet/'
              template: /bioentity/disease/Orphanet:{diseaseid}/phenotypes/
            - valueType: 'http://identifiers.org/doid/'
              template: /bioentity/disease/{diseaseid}/phenotypes/
      responses:
        '200':
          description: 'A distinct set of association.objects (typically ontology terms). This appears at the top level of the results payload'
          x-responseValueType:
            - path: objects
              valueType: 'http://identifiers.org/hp/'
          x-JSONLDContext:
            'biolink/jsonld_context/biolinks_phenotype_context.json'
  '/bioentity/gene/{geneid}/homologs':
    get:
      summary: 'Returns homologs for a gene'
      parameters:
        - name: geneid
          in: path
          description: >-
            CURIE identifier of gene, e.g. NCBIGene:4750. Equivalent IDs can be used with same results
          required: true
          schema:
            type: string
          x-valueType:
            - 'http://identifiers.org/ncbigene/'
          x-requestTemplate:
            - valueType: 'http://identifiers.org/ncbigene/'
              template: /bioentity/gene/NCBIGene:{geneid}/homologs/
      responses:
        '200':
          description: 'A distinct set of association.objects (typically ontology terms). This appears at the top level of the results payload'
          x-responseValueType:
            - path: edge.obj
              valueType: 'http://identifiers.org/mgi/'
            - path: edge.obj
              valueType: 'http://identifiers.org/zfin/'
            - path: edge.obj
              valueType: 'http://identifiers.org/ncbigene/'
          x-JSONLDContext:
            'biolink/jsonld_context/biolinks_homolog_context.json'
  '/bioentity/gene/{geneid}/interactions':
    get:
      summary: 'Returns interactions for a gene'
      parameters:
        - name: geneid
          in: path
          description: >-
            CURIE identifier of gene, e.g. NCBIGene:4750. Equivalent IDs can be used with same results
          required: true
          schema:
            type: string
          x-valueType:
            - 'http://identifiers.org/ncbigene/'
            - 'http://identifiers.org/hgnc/'
          x-requestTemplate:
            - valueType: 'http://identifiers.org/ncbigene/'
              template: /bioentity/gene/NCBIGene:{geneid}/interactions/
            - valueType: 'http://identifiers.org/hgnc/'
              template: /bioentity/gene/HGNC:{geneid}/interactions/
      responses:
        '200':
          description: 'A distinct set of association.objects (typically ontology terms). This appears at the top level of the results payload'
          x-responseValueType:
            - path: objects
              valueType: 'http://identifiers.org/ncbigene/'
            - path: objects
              valueType: 'http://identifiers.org/hgnc/'
          x-JSONLDContext:
            'biolink/jsonld_context/biolinks_interaction_context.json'
  '/bioentity/gene/{geneid}/phenotypes':
    get:
      summary: 'Returns phenotypes associated with gene'
      parameters:
        - name: geneid
          in: path
          description: >-
            CURIE identifier of gene, e.g. NCBIGene:4750. Equivalent IDs can be used with same results
          required: true
          schema:
            type: string
          x-valueType:
            - 'http://identifiers.org/ncbigene/'
            - 'http://identifiers.org/hgnc/'
          x-requestTemplate:
            - valueType: 'http://identifiers.org/ncbigene/'
              template: /bioentity/gene/NCBIGene:{geneid}/phenotypes
            - valueType: 'http://identifiers.org/hgnc/'
              template: /bioentity/gene/HGNC:{geneid}/phenotypes
      responses:
        '200':
          description: 'A distinct set of association.objects (typically ontology terms). This appears at the top level of the results payload'
          x-responseValueType:
            - path: edge.obj
              valueType: 'http://identifiers.org/hp/'
          x-JSONLDContext:
            'biolink/jsonld_context/biolinks_phenotype_context.json'
  '/bioentity/gene/{geneid}/pathways':
    get:
      summary: 'Returns pathways associated with gene'
      parameters:
        - name: geneid
          in: path
          description: >-
            CURIE identifier of gene, e.g. NCBIGene:4750. Equivalent IDs can be used with same results
          required: true
          schema:
            type: string
          x-valueType:
            - 'http://identifiers.org/ncbigene/'
            - 'http://identifiers.org/hgnc/'
          x-requestTemplate:
            - valueType: 'http://identifiers.org/ncbigene/'
              template: /bioentity/gene/NCBIGene:{geneid}/pathways
            - valueType: 'http://identifiers.org/hgnc/'
              template: /bioentity/gene/HGNC:{geneid}/pathways
      responses:
        '200':
          description: 'A distinct set of association.objects (typically ontology terms). This appears at the top level of the results payload'
          x-responseValueType:
            - path: edge.obj
              valueType: 'http://identifiers.org/reactome/'
          x-JSONLDContext:
            'biolink/jsonld_context/biolinks_pathway_context.json'
  '/bioentity/pathway/{pathwayid}/genes':
    get:
      summary: 'Returns genes associated with a pathway'
      parameters:
        - name: pathwayid
          in: path
          description: >-
            CURIE any pathway element. E.g. REACT:R-HSA-5387390
          required: true
          schema:
            type: string
          x-valueType:
            - 'http://identifiers.org/reactome/'
          x-requestTemplate:
            - valueType: 'http://identifiers.org/reactome/'
              template: /bioentity/pathway/REACT:{pathwayid}/genes
      responses:
        '200':
          description: 'A distinct set of association.objects (typically ontology terms). This appears at the top level of the results payload'
          x-responseValueType:
            - path: association.object.id
              valueType: 'http://identifiers.org/hgnc/'
          x-JSONLDContext:
            'biolink/jsonld_context/biolinks_gene_context.json'
  '/bioentity/variant/{variantid}/genes':
    get:
      summary: 'Returns genes associated with a variant'
      parameters:
        - name: variantid
          in: path
          description: >-
            CURIE identifier of variant, e.g. ZFIN:ZDB-ALT-010427-8, ClinVarVariant:39783
          required: true
          schema:
            type: string
          x-valueType:
            - 'http://identifiers.org/clinvar/'
          x-requestTemplate:
            - valueType: 'http://identifiers.org/clinvar/'
              template: /bioentity/variant/ClinVarVariant:{variantid}/genes
      responses:
        '200':
          description: 'A distinct set of association.objects (typically ontology terms). This appears at the top level of the results payload'
          x-responseValueType:
            - path: association.object.id
              valueType: 'http://identifiers.org/hgnc/'
          x-JSONLDContext:
            'biolink/jsonld_context/biolinks_variant2gene_context.json'
