openapi: 3.0.0
servers:
  - url: 'https://cmaq-dev.edc.renci.org/v1'
info:
  version: 1.0.0
  title: CMAQ Exposure API
  description: CMAQ Exposure API
  termsOfService: None
  contact:
    name: Michael J. Stealey
    url: 'https://github.com/renci/cmaq-exposure-api'
    email: stealey@renci.org
  license:
    name: MIT
    url: 'http://opensource.org/licenses/MIT'
paths:
  /variables:
    get:
      summary: CMAQ exposure variables
      description: CMAQ exposure variables
      parameters:
        - $ref: '#/components/parameters/search'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  variables:
                    type: array
                    items:
                      type: object
                      properties:
                        variable:
                          type: string
                          example: o3
                        description:
                          type: string
                          example: '1000.0*O3[1]'
                        has_quality_metric:
                          type: boolean
                          example: true
                        quality_metric:
                          type: array
                          items:
                            type: object
                            properties:
                              common_name:
                                type: string
                                example: root mean squared error
                              variable:
                                type: string
                                example: rmse
                        units:
                          type: string
                          example: ppbV
                        common_name:
                          type: string
                          example: ozone
                        utc_min_date_time:
                          type: string
                          format: date-time
                          example: '2010-01-01 00:00:00'
                        utc_max_date_time:
                          type: string
                          format: date-time
                          example: '2010-12-31 23:00:00'
                        resolution:
                          type: array
                          items:
                            type: string
                            example: hour;day;7day;14day
                        aggregation:
                          type: array
                          items:
                            type: string
                            example: avg;max
          x-responseValueType:
            - path: variables.variable
              valueType: https://github.com/lstillwe/cmaq-api-vocab/variable
            - path: variables.description
              valueType: http://schema.org/description
            - path: variables.has_quality_metric
              valueType: https://github.com/lstillwe/cmaq-api-vocab/has_quality_metric
            - path: variables.quality_metric
              valueType:https://github.com/lstillwe/cmaq-api-vocab/quality_metric
            - path: variables.quality_metric.common_name
              valueType: https://github.com/lstillwe/cmaq-api-vocab/common_name
            - path: variables.quality_metric.variable
              valueType: https://github.com/lstillwe/cmaq-api-vocab/qm_variable
            - path: variables.units
              valueType: http://purl.obolibrary.org/obo/ExO_0000066
            - path: variables.common_name
              valueType: https://github.com/lstillwe/cmaq-api-vocab/common_name
            - path: variables.utc_min_date_time
              valueType: http://schema.org/startDate
            - path: variables.utc_max_date_time
              valueType: http://schema.org/endDate
            - path: variables.resolution
              valueType: https://github.com/lstillwe/cmaq-api-vocab/resolution
            - path: variables.aggregation
              valueType: https://github.com/lstillwe/cmaq-api-vocab/aggregation
          x-JSONLDContext:
            'https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/GT_cmaq_exposures_api/jsonld_context/cmaq_exposures_api_context.json'
        '400':
          description: Invalid parameter
        '404':
          description: No exposure types found
        '500':
          description: Server error
  /values:
    get:
      summary: get values for exposure variable at location for date range
      description: get values for exposure variable at location for date range
      parameters:
        - $ref: '#/components/parameters/variable'
        - $ref: '#/components/parameters/start_date'
        - $ref: '#/components/parameters/end_date'
        - $ref: '#/components/parameters/lat_lon'
        - $ref: '#/components/parameters/resolution'
        - $ref: '#/components/parameters/aggregation'
        - $ref: '#/components/parameters/utc_offset'
        - $ref: '#/components/parameters/include_quality_metrics'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  values:
                    type: array
                    items:
                      type: object
                      properties:
                        variable:
                          type: string
                          example: o3
                        lat_lon:
                          type: string
                          example: '35,-80'
                        cmaq_output:
                          type: array
                          items:
                            type: object
                            properties:
                              date_time:
                                type: string
                                format: date-time
                                example: '2010-01-01 00:00:00'
                              value:
                                type: number
                                format: float
                                example: 49.8195953369141
                              quality_metric:
                                type: object
                                properties:
                                  cor:
                                    type: number
                                    format: float
                                    example: 0.54
                                  mb:
                                    type: number
                                    format: float
                                    example: 13.4852
                                  mod_mean:
                                    type: number
                                    format: float
                                    example: 31.6488
                                  obs_mean:
                                    type: number
                                    format: float
                                    example: 18.1636
                                  rmse:
                                    type: number
                                    format: float
                                    example: 18.7292
          x-responseValueType:
            - path: values.variable
              valueType: https://github.com/lstillwe/cmaq-api-vocab/variable
            - path: values.lat_lon
              valueType: https://github.com/lstillwe/cmaq-api-vocab/variable
            - path: values.cmaq_output.date_time
              valueType: http://schema.org/Date
            - path: values.cmaq_ouput.value
              valueType: http://schema.org/Float
            - path: values.cmaq_output.quality_metric.cor
              valueType: http://schema.org/Float
            - path: values.cmaq_output.quality_metric.mb
              valueType: http://schema.org/Float
            - path: values.cmaq_output.quality_metric.mode_mean
              valueType: http://schema.org/Float
            - path: values.cmaq_output.quality_metric.obs_mean
              valueType: http://schema.org/Float
            - path: values.cmaq_output.quality_metric.rmse
              valueType: http://schema.org/Float
          x-JSONLDContext:
            'https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/GT_cmaq_exposures_api/jsonld_context/cmaq_exposures_api_context.json'
        '400':
          description: Invalid parameter
        '404':
          description: No values found
        '500':
          description: Server error
components:
  parameters:
    search:
      name: search
      in: query
      description: search for exposure variable like - default is empty
      required: false
      schema:
        type: string
      x-valueType:
         - 'https://github.com/lstillwe/cmaq-api-vocab/'
      x-requestTemplate:
         - valueType: 'https://github.com/lstillwe/cmaq-api-vocab/'
           template: search
    variable:
      name: variable
      in: query
      description: cmaq variable - one or more seperated by ;
      required: true
      schema:
        type: string
      x-valueType:
         - 'https://github.com/lstillwe/cmaq-api-vocab/'
      x-requestTemplate:
         - valueType: 'https://github.com/lstillwe/cmaq-api-vocab/'
           template: variable
    start_date:
      name: start_date
      in: query
      description: start date of range
      required: true
      schema:
        type: string
        format: date
      x-valueType:
         - 'http://schema.org/'
      x-requestTemplate:
         - valueType: 'http://schema.org/'
           template: startDate
    end_date:
      name: end_date
      in: query
      description: end date of range
      required: true
      schema:
        type: string
        format: date
      x-valueType:
         - 'http://schema.org/'
      x-requestTemplate:
         - valueType: 'http://schema.org/'
           template: endDate
    lat_lon:
      name: lat_lon
      in: query
      description: 'latitude,longitude - one or more pairs seperated by ;'
      required: true
      schema:
        type: string
      x-valueType:
         - 'https://github.com/lstillwe/cmaq-api-vocab/'
      x-requestTemplate:
         - valueType: 'https://github.com/lstillwe/cmaq-api-vocab/'
           template: lat_lon
    resolution:
      name: resolution
      in: query
      description: 'temporal resolution (hour, day, 7day, 14day) - default is day'
      required: false
      schema:
        type: string
        default: day
      x-valueType:
         - 'https://github.com/lstillwe/cmaq-api-vocab/'
      x-requestTemplate:
         - valueType 'https://github.com/lstillwe/cmaq-api-vocab/'
           template: resolution
    aggregation:
      name: aggregation
      in: query
      description: 'numerical aggregation (max, avg) - default is max'
      required: false
      schema:
        type: string
        default: max
      x-valueType:
         - 'https://github.com/lstillwe/cmaq-api-vocab/'
      x-requestTemplate:
         - valueType: 'https://github.com/lstillwe/cmaq-api-vocab/'
           template: aggregation
    utc_offset:
      name: utc_offset
      in: query
      description: >-
        timezone offset from UTC (utc, eastern, central, mountain, pacific) -
        default is utc
      required: false
      schema:
        type: string
        default: utc
      x-valueType:
         - 'https://github.com/lstillwe/cmaq-api-vocab/'
      x-requestTemplate:
         - valueType: 'https://github.com/lstillwe/cmaq-api-vocab/'
           template: utc_offset
    include_quality_metrics:
      name: include_quality_metrics
      in: query
      description: >-
        if set to true, quality metrics, if available, will be returned with the
        selected variables - default is false
      required: false
      schema:
        type: boolean
        default: false
      x-valueType:
         - 'https://github.com/lstillwe/cmaq-api-vocab/'
      x-requestTemplate:
         - valueType: 'https://github.com/lstillwe/cmaq-api-vocab/'
           template: include_quality_metrics
